roots = [
  "^Database\\.Schema\\.Migrations\\.Backend\\.HDBC\\.hdbcBackend$",
  "^Database\\.Schema\\.Migrations\\.Test\\.BackendTest\\..*$",
  "^Main\\.main$",
  "^Moo\\.Core\\.makeParameters$",
  "^Moo\\.Main\\..*$",
  "^Paths_dbmigrations\\..*$",
  "^Spec\\.main$"
]
type-class-roots = true
